(* This file is part of Dream, released under the MIT license. See LICENSE.md
   for details, or visit https://github.com/aantron/dream.

   Copyright 2021 Anton Bachin *)



module Dream =
struct
  include Dream_pure
  include Dream_pure.Formats
end
(* This slightly awkward simulation of the overall Dream module using a
   composition of internal modules is necessary to get all the helpers at the
   right positions expected by the EML templater. *)



let render ~debug_dump ~code ~reason =
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <style>

      body {
        color: rgb(17, 24, 39);
        font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Open Sans, Helvetica Neue, Helvetica, Arial, sans-serif;
        margin: 3rem 2rem;
      }

      h1 {
        font-weight: 600;
        margin: 0;
      }

      h2 {
        font-weight: normal;
      }

      h3 {
        font-size: 16px;
        font-weight: normal;
        border: 1px solid #ddd;
        margin: 0;
        padding: 1rem 1.5rem;
      }

      pre {
        background-color: rgb(31, 41, 55);
        color: white;
        font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace;
        font-size: 16px;
        line-height: 1.5;
        margin: 0;
        padding: 1rem;
      }

      </style>
      <title><%i code %> <%s reason %></title>
    </head>

    <body>
      <h1>An error occured!</h1>
      <h2><%i code %> <%s reason %></h2>
      <p>
        This error page has been generated by Dream's error handler.<br />
        Remember to turn debugging mode off when deploying your application in
        production.
      </p>
      <h3>Debug Dump</h3>
      <pre><code><%s debug_dump %></code></pre>
    </body>
  </html>
