  $ debug &> /dev/null &
  $ $CURL localhost:8080/bad | sed 's/::1:.*/::1:<omitted>/' | sed 's/dream.request_id: [^<]*/dream.request_id: <omitted>/'
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <style>
  
      body {
        color: rgb(17, 24, 39);
        font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Open Sans, Helvetica Neue, Helvetica, Arial, sans-serif;
        margin: 3rem 2rem;
      }
  
      h1 {
        font-weight: 600;
        margin: 0;
      }
  
      h2 {
        font-weight: normal;
      }
  
      h3 {
        font-size: 16px;
        font-weight: normal;
        border: 1px solid #ddd;
        margin: 0;
        padding: 1rem 1.5rem;
      }
  
      pre {
        background-color: rgb(31, 41, 55);
        color: white;
        font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace;
        font-size: 16px;
        line-height: 1.5;
        margin: 0;
        padding: 1rem;
      }
  
      </style>
      <title>400 Bad Request</title>
    </head>
  
    <body>
      <h1>An error occured!</h1>
      <h2>400 Bad Request</h2>
      <p>
        This error page has been generated by Dream's error handler.<br />
        Remember to turn debugging mode off when deploying your application in
        production.
      </p>
      <h3>Debug Dump</h3>
      <pre><code>400 Bad Request
  
  From: Application
  Blame: Client
  Severity: Warning
  
  Client: ::1:<omitted>
  
  GET /bad
  Host: localhost:8080
  User-Agent: curl/8.9.1
  Accept: */*
  
  dream.client: ::1:<omitted>
  dream.tls: false
  dream.request_id: <omitted>
  dream.fd: 6
  dream.params: </code></pre>
    </body>
  </html>
  $ $CURL localhost:8080/fail | sed 's/::1:.*/::1:<omitted>/' | sed 's/dream.request_id: [^<]*/dream.request_id: <omitted>/'
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <style>
  
      body {
        color: rgb(17, 24, 39);
        font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Open Sans, Helvetica Neue, Helvetica, Arial, sans-serif;
        margin: 3rem 2rem;
      }
  
      h1 {
        font-weight: 600;
        margin: 0;
      }
  
      h2 {
        font-weight: normal;
      }
  
      h3 {
        font-size: 16px;
        font-weight: normal;
        border: 1px solid #ddd;
        margin: 0;
        padding: 1rem 1.5rem;
      }
  
      pre {
        background-color: rgb(31, 41, 55);
        color: white;
        font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace;
        font-size: 16px;
        line-height: 1.5;
        margin: 0;
        padding: 1rem;
      }
  
      </style>
      <title>500 Internal Server Error</title>
    </head>
  
    <body>
      <h1>An error occured!</h1>
      <h2>500 Internal Server Error</h2>
      <p>
        This error page has been generated by Dream's error handler.<br />
        Remember to turn debugging mode off when deploying your application in
        production.
      </p>
      <h3>Debug Dump</h3>
      <pre><code>Failure(&quot;The Web app failed!&quot;)
  Raised at Stdlib__Map.Make.find in file &quot;map.ml&quot;, line 141, characters 10-25
  Called from Logs.Tag.find in file &quot;src/logs.ml&quot;, line 153, characters 14-32
  
  From: Application
  Blame: Server
  Severity: Error
  
  Client: ::1:<omitted>
  
  GET /fail
  Host: localhost:8080
  User-Agent: curl/8.9.1
  Accept: */*
  
  dream.client: ::1:<omitted>
  dream.tls: false
  dream.request_id: <omitted>
  dream.fd: 6
  dream.params: </code></pre>
    </body>
  </html>
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <style>
  
      body {
        color: rgb(17, 24, 39);
        font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Open Sans, Helvetica Neue, Helvetica, Arial, sans-serif;
        margin: 3rem 2rem;
      }
  
      h1 {
        font-weight: 600;
        margin: 0;
      }
  
      h2 {
        font-weight: normal;
      }
  
      h3 {
        font-size: 16px;
        font-weight: normal;
        border: 1px solid #ddd;
        margin: 0;
        padding: 1rem 1.5rem;
      }
  
      pre {
        background-color: rgb(31, 41, 55);
        color: white;
        font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace;
        font-size: 16px;
        line-height: 1.5;
        margin: 0;
        padding: 1rem;
      }
  
      </style>
      <title>500 Internal Server Error</title>
    </head>
  
    <body>
      <h1>An error occured!</h1>
      <h2>500 Internal Server Error</h2>
      <p>
        This error page has been generated by Dream's error handler.<br />
        Remember to turn debugging mode off when deploying your application in
        production.
      </p>
      <h3>Debug Dump</h3>
      <pre><code>Failure(&quot;The Web app failed!&quot;)
  Raised at Stdlib__Map.Make.find in file &quot;map.ml&quot;, line 141, characters 10-25
  Called from Logs.Tag.find in file &quot;src/logs.ml&quot;, line 153, characters 14-32
  
  From: Application
  Blame: Server
  Severity: Error
  
  Client: ::1:<omitted>
  
  GET /fail
  Host: localhost:8080
  User-Agent: curl/8.9.1
  Accept: */*
  
  dream.client: ::1:<omitted>
  dream.tls: false
  dream.request_id: <omitted>
  dream.fd: 6
  dream.params: </code></pre>
    </body>
  </html>
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <style>
  
      body {
        color: rgb(17, 24, 39);
        font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Open Sans, Helvetica Neue, Helvetica, Arial, sans-serif;
        margin: 3rem 2rem;
      }
  
      h1 {
        font-weight: 600;
        margin: 0;
      }
  
      h2 {
        font-weight: normal;
      }
  
      h3 {
        font-size: 16px;
        font-weight: normal;
        border: 1px solid #ddd;
        margin: 0;
        padding: 1rem 1.5rem;
      }
  
      pre {
        background-color: rgb(31, 41, 55);
        color: white;
        font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace;
        font-size: 16px;
        line-height: 1.5;
        margin: 0;
        padding: 1rem;
      }
  
      </style>
      <title>500 Internal Server Error</title>
    </head>
  
    <body>
      <h1>An error occured!</h1>
      <h2>500 Internal Server Error</h2>
      <p>
        This error page has been generated by Dream's error handler.<br />
        Remember to turn debugging mode off when deploying your application in
        production.
      </p>
      <h3>Debug Dump</h3>
      <pre><code>Failure(&quot;The Web app failed!&quot;)
  Raised at Stdlib__Map.Make.find in file &quot;map.ml&quot;, line 141, characters 10-25
  Called from Logs.Tag.find in file &quot;src/logs.ml&quot;, line 153, characters 14-32
  
  From: Application
  Blame: Server
  Severity: Error
  
  Client: ::1:<omitted>
  
  GET /fail
  Host: localhost:8080
  User-Agent: curl/8.9.1
  Accept: */*
  
  dream.client: ::1:<omitted>
  dream.tls: false
  dream.request_id: <omitted>
  dream.fd: 6
  dream.params: </code></pre>
    </body>
  </html>
  $ pkill -P $$
