(* This is a dummy version of a file that is generated by a script. The
   purpose of this dummy file is to suppress spurious build errors when
   a build system looks for this file as a dependency. *)

let list = []
